### ISSUE TITLE
Rails 7 support?

### ISSUE THREAD

**Issue by aforty** [foundation/inky-rb#109]
I just updated to rails 7 and I can't seem to get this to load. It looks like it never registers the inky extension. Has anyone gotten this to work?

**Comment by daniel-rikowski** [comment]
I'm using Inky with Rails 7 and Ruby 3.1 on Windows and Alma Linux.

I do use a simple monkey patch to remove layout breaking whitespace from the generated HTML, but this is for an Inky bug, and not related to the Rails version.

**Comment by phoet** [comment]
looks like its completely gone with rails 7.1

inky-rb-1.4.2.0/lib/inky.rb:38:in `release_the_kraken'

NoMethodError:
     #   undefined method `gsub' for #<ActionView::OutputBuffer

**Comment by zealot128** [comment]
I've made a simple change, it seems to work with Rails 7.1.beta1 now:

https://github.com/foundation/inky-rb/pull/110

**Comment by joeworkman** [comment]
This repository is being sunset. The Inky project is being rewritten in Rust with a single canonical core and official bindings for all major languages — including a new Ruby gem that uses the shared Rust core via FFI (fiddle).

This means:
- One implementation, identical output across all languages
- No more Ruby-specific bugs or maintenance burden
- The new Ruby gem will have zero gem dependencies (fiddle is in Ruby's stdlib)

You can follow progress at https://github.com/foundation/inky.

Thanks for using inky-rb!
